version: 0.2
env:
  variables:
    AWS_XRAY_LOG_LEVEL: 'silent'
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      # install server dependencies
      - npm install --prefix get-properties
      - npm install --prefix get-property
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      # Build app
      - sam build
      # Run Unit Tests
      - npm run test --prefix get-properties
      - npm run test --prefix get-property
      # Package SAM template
      - echo Packaging started on `date`
      - sam package --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-chfgod7k1eyc --s3-prefix packaged-functions --output-template-file .aws-sam/packaged.yaml
artifacts:
  files:
    - '**/*'
  discard-paths: no
