version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      #Lambda deploy reference
      #https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html
      #Build spec reference
      #https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
      # Package SAM template
      - sam build
      # - sam package --template-file sam_template.yml --s3-bucket sam-artifacts-sou --output-template-file packaged.yaml
      # Deploy packaged SAM template
      - sam deploy --stack-name hauzzy-serverless-stack --no-confirm-changeset --capabilities CAPABILITY_NAMED_IAM
