version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hauzzy-serverless-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-chfgod7k1eyc"
s3_prefix = "hauzzy-serverless-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
