openapi: 3.0.0

info:
  title: hauzzy-serverless-api
  version: 1.0.0

servers:
  - url: http://www.hauzzy.com

paths:
  /api/properties:
    get:
      summary: Returns a list of properties.
      responses:
        '200':
          description: A JSON object
          content:
            application/json:
              schema: 
                type: object
                properties:
                  properties:
                    type: array
                    description: List of active listings
                  count:
                    type: integer
                    description: Numer representing number of listings returned
        '500':
          description: Unexpected error.
      x-amazon-apigateway-integration:
        httpMethod: post
        type: aws_proxy
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPropertiesFunction.Arn}/invocations"