AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for hauzzy-serverless
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
    Architectures:
        - arm64

Resources:
  HauzzyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      # DefinitionUri: swagger.yaml
      
  GetPropertiesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn: ParameterStoreCredentialsRole
    Properties:
      FunctionName: GetPropertiesFunction
      CodeUri: get-properties/
      Handler: app.lambdaHandler
      MemorySize: 256
      Role: !GetAtt ParameterStoreCredentialsRole.Arn
      Events:
        GetPropertiesApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/properties
            Method: get
            RestApiId:
              Ref: HauzzyApi
  
  ParameterStoreCredentialsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        -
          PolicyName: 'ParameterStoreAccess'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - 'ssm:GetParameter*'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/db*'

  ParameterStoreEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: 'alias/ParameterStoreKeySAM'
      TargetKeyId: !Ref ParameterStoreEncryptionKey

  ParameterStoreEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'Encryption key for secret config values for the Parameter Store'
      Enabled: True
      EnableKeyRotation: False
      KeyPolicy:
        Version: '2012-10-17'
        Id: 'key-default-1'
        Statement:
          -
            Sid: 'Allow administration of the key & encryption of new values'
            Effect: Allow
            Principal:
              AWS:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:user/Administrator'
            Action:
              - 'kms:Create*'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          -
            Sid: 'Allow use of the key'
            Effect: Allow
            Principal:
              AWS: !GetAtt ParameterStoreCredentialsRole.Arn
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HauzzyApi:
  #   Description: "API Gateway endpoint URL for Prod stage for properties function"
  #   Value: !Sub "https://${HauzzyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GetPropertiesFunction:
    Description: "GetPropertiesFunction Lambda Function ARN"
    Value: !GetAtt GetPropertiesFunction.Arn
  # GetPropertiesFunctionIamRole:
  #   Description: "Implicit IAM Role created for GetPropertiesFunction function"
  #   Value: !GetAtt GetPropertiesFunctionRole.Arn
