AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for hauzzy-serverless
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 30
    Architectures:
        - arm64

Resources:
  HauzzyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      # DefinitionUri: swagger.yaml
      
  GetPropertiesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetPropertiesFunction
      CodeUri: get-properties/
      Handler: app.lambdaHandler
      MemorySize: 256
      Events:
        GetPropertiesApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/properties
            Method: get
            RestApiId:
              Ref: HauzzyApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HauzzyApi:
  #   Description: "API Gateway endpoint URL for Prod stage for properties function"
  #   Value: !Sub "https://${HauzzyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GetPropertiesFunction:
    Description: "GetPropertiesFunction Lambda Function ARN"
    Value: !GetAtt GetPropertiesFunction.Arn
  GetPropertiesFunctionIamRole:
    Description: "Implicit IAM Role created for GetPropertiesFunction function"
    Value: !GetAtt GetPropertiesFunctionRole.Arn
